#!/usr/bin/env node
// T11 — Verify §10.6: "The PixiJS render looks like a REAL product —
// polished gradients, composited typography, visual depth — because the
// atlas was generated by fal.ai FLUX.2 against a style-locked reference,
// not from hand-drawn primitives."
//
// Spec ref: §10.6 (extract L1176, criterion #6)
//
// T11 reframes the subjective "looks like a real product" criterion as an
// objective pixel-regression test: a screenshot of the live preview pane at
// a locked viewport (1440×900) is compared byte-by-byte against a baseline
// committed to `tests/fixtures/home-hub-hero.png`. Any change to the atlas,
// the node graph, node layout, or the boot sequence will shift pixels; a
// shift larger than 2% of the screenshot fails the test.
//
// The baseline is generated by running with `UPDATE_BASELINE=1` the first
// time (or whenever the mock app's intended visual surface changes). The
// baseline file is committed alongside the test; subsequent runs diff
// against it.
//
// Acceptance contract on the running dev app at viewport 1440×900:
//
//   (A) INFRASTRUCTURE
//       A1 server boots, `/` → HTTP 200
//       A2 page.goto(/) → HTTP 200
//       A3 __prism exposed, home-hub nodes mounted, hero-section-bg
//          NodeInstance present
//       A4 [data-pane="preview"] locator resolves (T05's DOM contract)
//
//   (B) STABILIZE — the visual surface must be deterministic so that two
//       consecutive runs produce the same screenshot.
//       B1 all setInterval IDs cleared (pauses hero-section-bg's 24fps
//          frame cycle) — count >= 1
//       B2 hero-section-bg container children collapsed to frame 0 only
//       B3 PIXI ticker rendered at least one post-pause frame (waitForTimeout)
//
//   (C) CAPTURE
//       C1 [data-pane="preview"] screenshot taken (PNG buffer)
//       C2 screenshot is a valid PNG (starts with \x89PNG magic)
//       C3 screenshot is non-empty (>10 KB — empty/black frames are <1 KB)
//
//   (D) BASELINE + DIFF (skipped when UPDATE_BASELINE=1)
//       D1 baseline file exists at tests/fixtures/home-hub-hero.png
//       D2 baseline + screenshot have matching dimensions
//       D3 pixel diff fraction <= 0.02 (2%)
//       D4 when diff > 0, a side-by-side `tests/fixtures/T11-actual.png`
//          and `tests/fixtures/T11-diff.png` are written for debugging
//
//   (E) UPDATE MODE (only when UPDATE_BASELINE=1)
//       E1 screenshot buffer written to tests/fixtures/home-hub-hero.png
//       E2 readback matches the written buffer byte-for-byte
//
// Port 4787 — avoids 4777..4786 used by earlier tests.
//
// Run: node tests/lib/prism/player/T11.test.mjs
//      UPDATE_BASELINE=1 node tests/lib/prism/player/T11.test.mjs

import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..', '..', '..', '..');
const appRoot = join(repoRoot, 'kid-kode-landing');
const fixturesDir = join(repoRoot, 'tests', 'fixtures');
const baselinePath = join(fixturesDir, 'home-hub-hero.png');
const actualPath = join(fixturesDir, 'T11-actual.png');
const diffPath = join(fixturesDir, 'T11-diff.png');

const UPDATE = process.env.UPDATE_BASELINE === '1';
const PORT = 4787;
const URL = `http://localhost:${PORT}/`;

const GREEN = '\x1b[32m', RED = '\x1b[31m', DIM = '\x1b[2m', RESET = '\x1b[0m';
const failures = [];
function check(label, pass, detail = '') {
  const marker = pass ? `${GREEN}PASS${RESET}` : `${RED}FAIL${RESET}`;
  console.log(`[${marker}] ${label}${detail ? `  ${DIM}${detail}${RESET}` : ''}`);
  if (!pass) failures.push({ label, detail });
}

async function waitForServer(url, timeoutMs = 120000) {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    try {
      const res = await fetch(url);
      if (res.ok) return true;
    } catch { /* still booting */ }
    await new Promise((r) => setTimeout(r, 500));
  }
  return false;
}

// Per-pixel RGB threshold: absolute channel delta <= 16 counts as "same".
// §10.6 is about gross visual surface; sub-threshold AA jitter around text
// edges and gradient bands should not trip the regression.
const CHANNEL_THRESHOLD = 16;

async function pixelDiff(pathA, bufB) {
  const requireCjs = createRequire(join(appRoot, 'package.json'));
  const sharp = requireCjs('sharp');
  const a = await sharp(pathA).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  const b = await sharp(bufB).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  if (a.info.width !== b.info.width || a.info.height !== b.info.height) {
    return {
      dimsMatch: false,
      diffFrac: 1,
      aW: a.info.width, aH: a.info.height,
      bW: b.info.width, bH: b.info.height,
    };
  }
  const W = a.info.width, H = a.info.height;
  const pixels = W * H;
  let diffCount = 0;
  const diffImg = Buffer.alloc(pixels * 4);
  for (let i = 0; i < pixels; i++) {
    const off = i * 4;
    const dr = Math.abs(a.data[off] - b.data[off]);
    const dg = Math.abs(a.data[off + 1] - b.data[off + 1]);
    const db = Math.abs(a.data[off + 2] - b.data[off + 2]);
    if (dr > CHANNEL_THRESHOLD || dg > CHANNEL_THRESHOLD || db > CHANNEL_THRESHOLD) {
      diffCount++;
      diffImg[off] = 0xff;     // red highlight on diff pixels
      diffImg[off + 1] = 0x00;
      diffImg[off + 2] = 0x00;
      diffImg[off + 3] = 0xff;
    } else {
      // faded baseline under matching pixels
      diffImg[off] = (a.data[off] * 0.3) | 0;
      diffImg[off + 1] = (a.data[off + 1] * 0.3) | 0;
      diffImg[off + 2] = (a.data[off + 2] * 0.3) | 0;
      diffImg[off + 3] = 0xff;
    }
  }
  return {
    dimsMatch: true,
    diffFrac: diffCount / pixels,
    pixels,
    diffCount,
    W, H,
    diffBuffer: await sharp(diffImg, { raw: { width: W, height: H, channels: 4 } }).png().toBuffer(),
  };
}

async function main() {
  // Run the dev server in its own process group so a single kill(-pgid) takes
  // down npm, `next dev`, and the grandchild `next-server` in one go. Without
  // this, `server.kill()` only signals npm and the grandchild keeps running
  // (and keeps the test's stdout-pipe-read side alive, stalling exit).
  const server = spawn('npm', ['run', 'dev', '--', '-p', String(PORT)], {
    cwd: appRoot,
    stdio: ['ignore', 'pipe', 'pipe'],
    env: { ...process.env, BROWSER: 'none' },
    detached: true,
  });
  const serverLog = [];
  server.stdout.on('data', (b) => serverLog.push(b.toString()));
  server.stderr.on('data', (b) => { serverLog.push(b.toString()); });

  let browser;
  try {
    const ok = await waitForServer(URL);
    check('§10.6 A1 — `/` responds with HTTP 200',
      ok, ok ? `ready at ${URL}` : `server did not come up in 120s — tail:\n${serverLog.join('').slice(-2000)}`);
    if (!ok) return;

    const { chromium } = await import(join(appRoot, 'node_modules', 'playwright', 'index.mjs'));
    browser = await chromium.launch();
    const context = await browser.newContext({
      viewport: { width: 1440, height: 900 },
      deviceScaleFactor: 1,
    });

    // Instrument setInterval before any page script runs so we can pause
    // hero-section-bg's i2v frame cycle for a deterministic screenshot.
    await context.addInitScript(() => {
      const ids = new Set();
      const origSet = window.setInterval;
      const origClear = window.clearInterval;
      window.setInterval = function (fn, ms, ...args) {
        const id = origSet.call(window, fn, ms, ...args);
        ids.add(id);
        return id;
      };
      window.clearInterval = function (id) {
        ids.delete(id);
        return origClear.call(window, id);
      };
      window.__clearAllIntervals = () => {
        const n = ids.size;
        for (const id of ids) origClear.call(window, id);
        ids.clear();
        return n;
      };
    });

    const page = await context.newPage();
    page.on('pageerror', (e) => console.error('[T11 pageerror]', e.message));

    const response = await page.goto(URL, { waitUntil: 'load' });
    check('§10.6 A2 — page.goto(`/`) resolves with HTTP 200',
      !!response && response.status() === 200, `status=${response?.status()}`);

    const ready = await page.waitForFunction(() => {
      const p = /** @type {any} */ (window).__prism;
      return !!(p && p.nodes && p.nodes.has('hero-section-bg') && p.nodes.has('hero-card-cta'));
    }, null, { timeout: 30000 })
      .then(() => true)
      .catch(() => false);
    check('§10.6 A3 — __prism exposed + hero-section-bg + hero-card-cta mounted',
      ready,
      ready ? '' : `__prism never exposed expected nodes — tail:\n${serverLog.join('').slice(-1000)}`);
    if (!ready) return;

    const previewBounds = await page.evaluate(() => {
      const el = document.querySelector('[data-pane="preview"]');
      if (!el) return null;
      const r = el.getBoundingClientRect();
      return { x: r.x, y: r.y, w: r.width, h: r.height };
    });
    check('§10.6 A4 — [data-pane="preview"] locator resolves with non-zero bounds',
      !!previewBounds && previewBounds.w > 100 && previewBounds.h > 100,
      `bounds=${JSON.stringify(previewBounds)}`);
    if (!previewBounds) return;

    // (B) Stabilize.
    const clearedCount = await page.evaluate(() => /** @type {any} */ (window).__clearAllIntervals());
    check('§10.6 B1 — setInterval IDs cleared (pauses hero-section-bg frame cycle)',
      clearedCount >= 1, `cleared=${clearedCount}`);

    const collapsed = await page.evaluate(() => {
      const p = /** @type {any} */ (window).__prism;
      const inst = p.nodes.get('hero-section-bg');
      if (!inst || !inst.container || !inst.container.children) return { ok: false, kids: 0 };
      const kids = inst.container.children;
      let visible0 = 0, hiddenOthers = 0;
      kids.forEach((s, i) => {
        s.visible = i === 0;
        if (i === 0 && s.visible) visible0++;
        if (i !== 0 && !s.visible) hiddenOthers++;
      });
      return { ok: true, total: kids.length, visible0, hiddenOthers };
    });
    check('§10.6 B2 — hero-section-bg collapsed to frame 0',
      collapsed.ok && collapsed.visible0 === 1 && collapsed.hiddenOthers === (collapsed.total - 1),
      `state=${JSON.stringify(collapsed)}`);

    // Let the PIXI ticker render at least one post-pause frame.
    await page.waitForTimeout(250);
    check('§10.6 B3 — post-pause render grace elapsed', true, 'waited 250ms');

    // (C) Capture.
    const previewLocator = page.locator('[data-pane="preview"]');
    const shot = await previewLocator.screenshot({ type: 'png' });
    check('§10.6 C1 — [data-pane="preview"] screenshot captured',
      Buffer.isBuffer(shot) && shot.length > 0,
      `bytes=${shot?.length}`);

    const isPng = shot.length >= 8 &&
      shot[0] === 0x89 && shot[1] === 0x50 && shot[2] === 0x4e && shot[3] === 0x47 &&
      shot[4] === 0x0d && shot[5] === 0x0a && shot[6] === 0x1a && shot[7] === 0x0a;
    check('§10.6 C2 — screenshot is a valid PNG (magic bytes)',
      isPng, `header=${[...shot.slice(0, 8)].map((b) => b.toString(16).padStart(2, '0')).join(' ')}`);

    check('§10.6 C3 — screenshot is non-empty (>10 KB)',
      shot.length > 10_000, `bytes=${shot.length}`);

    // Ensure fixtures dir exists regardless of UPDATE mode.
    if (!existsSync(fixturesDir)) mkdirSync(fixturesDir, { recursive: true });

    if (UPDATE) {
      writeFileSync(baselinePath, shot);
      check('§10.6 E1 — baseline written to tests/fixtures/home-hub-hero.png',
        existsSync(baselinePath), baselinePath);
      const readBack = readFileSync(baselinePath);
      check('§10.6 E2 — readback matches written buffer',
        readBack.equals(shot), `wrote=${shot.length} read=${readBack.length}`);
    } else {
      const haveBaseline = existsSync(baselinePath);
      check('§10.6 D1 — baseline exists at tests/fixtures/home-hub-hero.png',
        haveBaseline,
        haveBaseline ? baselinePath : `missing — run UPDATE_BASELINE=1 node tests/lib/prism/player/T11.test.mjs to generate`);
      if (!haveBaseline) return;

      const diff = await pixelDiff(baselinePath, shot);
      check('§10.6 D2 — baseline + screenshot have matching dimensions',
        diff.dimsMatch,
        diff.dimsMatch ? `${diff.W}x${diff.H}` : `baseline=${diff.aW}x${diff.aH} actual=${diff.bW}x${diff.bH}`);
      if (!diff.dimsMatch) return;

      const pct = (diff.diffFrac * 100).toFixed(3);
      check('§10.6 D3 — pixel diff fraction <= 2% (T11 tolerance)',
        diff.diffFrac <= 0.02,
        `diff=${pct}% (${diff.diffCount}/${diff.pixels} px, threshold ${CHANNEL_THRESHOLD}/chan)`);

      if (diff.diffFrac > 0) {
        writeFileSync(actualPath, shot);
        writeFileSync(diffPath, diff.diffBuffer);
        check('§10.6 D4 — actual + diff written for debugging (diff>0)',
          existsSync(actualPath) && existsSync(diffPath),
          `actual=${actualPath} diff=${diffPath}`);
      } else {
        check('§10.6 D4 — actual + diff not needed (diff == 0)',
          true, 'skipped — baseline matches exactly');
      }
    }
  } catch (e) {
    check('fatal', false, e.stack ?? e.message ?? String(e));
  } finally {
    // Once we enter cleanup, cap the tail of the process at 10s. If the
    // browser handle or the child process group refuses to close cleanly,
    // the test's assertion output has already been flushed above; we just
    // need to exit so the Ralph loop can advance.
    const forceExit = setTimeout(() => {
      console.log(`${RED}T11: force-exit after cleanup stalled${RESET}`);
      process.exit(failures.length === 0 ? 0 : 1);
    }, 10000);
    forceExit.unref?.();

    // browser.close() occasionally hangs in headless Chromium after a failing
    // screenshot; race it with a 3s timeout so the test doesn't stall after
    // its last assertion.
    try {
      if (browser) {
        await Promise.race([
          browser.close(),
          new Promise((r) => setTimeout(r, 3000)),
        ]);
      }
    } catch { /* ignore */ }
    // Kill the whole dev-server process group (npm + next + next-server).
    try {
      if (server.pid) process.kill(-server.pid, 'SIGKILL');
    } catch {
      try { server.kill('SIGKILL'); } catch { /* ignore */ }
    }
    // Detach stdout/stderr listeners so the readable streams do not keep
    // Node's event loop alive after the child is gone.
    try { server.stdout?.removeAllListeners(); server.stdout?.destroy(); } catch { /* ignore */ }
    try { server.stderr?.removeAllListeners(); server.stderr?.destroy(); } catch { /* ignore */ }
    await new Promise((r) => setTimeout(r, 300));
  }

  if (failures.length === 0) {
    console.log(`\n${GREEN}T11: all §10.6 checks passed${UPDATE ? ' (UPDATE mode)' : ''}${RESET}`);
    process.exit(0);
  } else {
    console.log(`\n${RED}T11: ${failures.length} check(s) failed${RESET}`);
    process.exit(1);
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
