// Prebuilt element catalog barrel (§13). AUTO-GENERATED by
// scripts/regen-element-barrel.mjs — do not hand-edit; re-run the script.
//
// Seeds use named export + explicit register; every other element self-
// registers on import (side-effect import). One import of this barrel
// registers the whole library — drawn from by the browser + AI authoring.

import { registerElement } from '../registry';
import { carouselPhotorealRing } from './carousel-photoreal-ring';
import { heroPhotorealMonolith } from './hero-photoreal-monolith';

// Self-registering elements (side-effect imports):
import './banner-light-sweep';
import './banner-silk-flag';
import './banner-ticker-3d';
import './cardstack-fan-spread';
import './cardstack-swipe-deck';
import './carousel-coverflow-depth';
import './carousel-cylinder-billboard';
import './cta-glass-banner';
import './cta-magnetic-pedestal';
import './featuregrid-depth-pop';
import './featuregrid-tilt-cards';
import './gallery-depth-wall';
import './gallery-masonry-reveal';
import './hero-glass-prism';
import './hero-liquid-metal';
import './hero-particle-emerge';
import './logocloud-constellation';
import './logocloud-orbital';
import './marquee-ribbon-flow';
import './nav-glass-dock';
import './nav-orbital-ring';
import './pricing-glass-tiers';
import './pricing-pillars-3d';
import './showcase-exploded';
import './showcase-turntable';
import './slider-depth-parallax';
import './slider-distortion-fade';
import './slider-morph-through';
import './stats-odometer';
import './stats-ring-progress';
import './testimonial-float-glass';
import './testimonial-orbit-quotes';
import './wheel-fortune-spinner';
import './wheel-radial-menu';

let registered = false;
/** Idempotent: register the seed elements (the rest self-register on import). */
export function registerAllElements(): void {
  if (registered) return;
  registerElement(carouselPhotorealRing);
  registerElement(heroPhotorealMonolith);
  registered = true;
}

registerAllElements();

export { carouselPhotorealRing } from './carousel-photoreal-ring';
export { heroPhotorealMonolith } from './hero-photoreal-monolith';
