// Catalog manifest — imports every primitive definition and registers it.
// Importing this module populates the Animatable registry (side-effect on first
// import). AUTO-GENERATED by notes/catalog-wire-barrel.mjs after each parallel
// fan-out — ordered by category then name. Do not hand-edit; re-run the wirer.

import { registerPrimitive } from '../registry';
import type { PrimitiveDefinition } from '../contract';

import { bouncePrimitive } from './bounce';
import { elasticPrimitive } from './elastic';
import { flipPrimitive } from './flip';
import { floatPrimitive } from './float';
import { jellyPrimitive } from './jelly';
import { overshootPrimitive } from './overshoot';
import { rotateInPrimitive } from './rotate-in';
import { scalePopPrimitive } from './scale-pop';
import { slidePrimitive } from './slide';
import { spinPrimitive } from './spin';
import { swingPrimitive } from './swing';
import { blinkPrimitive } from './blink';
import { dissolveNoisePrimitive } from './dissolve-noise';
import { fadePrimitive } from './fade';
import { fadeThroughBlackPrimitive } from './fade-through-black';
import { flashPrimitive } from './flash';
import { horizontalScrollPrimitive } from './horizontal-scroll';
import { parallaxPrimitive } from './parallax';
import { pinRevealPrimitive } from './pin-reveal';
import { revealMaskScrollPrimitive } from './reveal-mask-scroll';
import { scrollRotate3dPrimitive } from './scroll-rotate-3d';
import { scrubMorphPrimitive } from './scrub-morph';
import { stickyPinPrimitive } from './sticky-pin';
import { cursorTrailPrimitive } from './cursor-trail';
import { hoverLiftPrimitive } from './hover-lift';
import { magneticPrimitive } from './magnetic';
import { parallaxLayersPrimitive } from './parallax-layers';
import { repelPrimitive } from './repel';
import { tiltPrimitive } from './tilt';
import { dissolveToDustPrimitive } from './dissolve-to-dust';
import { glitchTextPrimitive } from './glitch-text';
import { neonFlickerTextPrimitive } from './neon-flicker-text';
import { scramblePrimitive } from './scramble';
import { splitStaggerPrimitive } from './split-stagger';
import { textCascadePrimitive } from './text-cascade';
import { textExtrudePrimitive } from './text-extrude';
import { typewriterPrimitive } from './typewriter';
import { waveTextPrimitive } from './wave-text';
import { flagWavePrimitive } from './flag-wave';
import { foamPrimitive } from './foam';
import { inkSpreadPrimitive } from './ink-spread';
import { jellySurfacePrimitive } from './jelly-surface';
import { oceanFftPrimitive } from './ocean-fft';
import { ripplePrimitive } from './ripple';
import { ripplePoolPrimitive } from './ripple-pool';
import { wavePrimitive } from './wave';
import { displacementTransitionPrimitive } from './displacement-transition';
import { glitchDisplacePrimitive } from './glitch-displace';
import { meltPrimitive } from './melt';
import { pixelDissolvePrimitive } from './pixel-dissolve';
import { shatterPrimitive } from './shatter';
import { irisWipePrimitive } from './iris-wipe';
import { maskWipePrimitive } from './mask-wipe';
import { blurInPrimitive } from './blur-in';
import { zoomBlurPrimitive } from './zoom-blur';
import { holographicPrimitive } from './holographic';
import { iridescencePrimitive } from './iridescence';
import { metallicSheenPrimitive } from './metallic-sheen';
import { shimmerPrimitive } from './shimmer';
import { sparkleGlintsPrimitive } from './sparkle-glints';
import { crystalFacetPrimitive } from './crystal-facet';
import { dispersionPrimitive } from './dispersion';
import { fresnelGlowPrimitive } from './fresnel-glow';
import { frostedGlassPrimitive } from './frosted-glass';
import { glassRefractionPrimitive } from './glass-refraction';
import { iridescentGlassPrimitive } from './iridescent-glass';
import { liquidGlassPrimitive } from './liquid-glass';
import { refractionWarpPrimitive } from './refraction-warp';
import { causticsPrimitive } from './caustics';
import { causticsRipplePrimitive } from './caustics-ripple';
import { underwaterCausticsPrimitive } from './underwater-caustics';
import { cloudsPrimitive } from './clouds';
import { fireFlamePrimitive } from './fire-flame';
import { fogPrimitive } from './fog';
import { godrayPrimitive } from './godray';
import { lightShaftsPrimitive } from './light-shafts';
import { nebulaPrimitive } from './nebula';
import { plasmaPrimitive } from './plasma';
import { smokePrimitive } from './smoke';
import { steamPrimitive } from './steam';
import { wispySmokePrimitive } from './wispy-smoke';
import { bubblesPrimitive } from './bubbles';
import { confettiPrimitive } from './confetti';
import { dustParticlesPrimitive } from './dust-particles';
import { embersPrimitive } from './embers';
import { firefliesPrimitive } from './fireflies';
import { fountainPrimitive } from './fountain';
import { rainPrimitive } from './rain';
import { snowPrimitive } from './snow';
import { sparksPrimitive } from './sparks';

export const ALL_PRIMITIVES: PrimitiveDefinition[] = [
  bouncePrimitive,
  elasticPrimitive,
  flipPrimitive,
  floatPrimitive,
  jellyPrimitive,
  overshootPrimitive,
  rotateInPrimitive,
  scalePopPrimitive,
  slidePrimitive,
  spinPrimitive,
  swingPrimitive,
  blinkPrimitive,
  dissolveNoisePrimitive,
  fadePrimitive,
  fadeThroughBlackPrimitive,
  flashPrimitive,
  horizontalScrollPrimitive,
  parallaxPrimitive,
  pinRevealPrimitive,
  revealMaskScrollPrimitive,
  scrollRotate3dPrimitive,
  scrubMorphPrimitive,
  stickyPinPrimitive,
  cursorTrailPrimitive,
  hoverLiftPrimitive,
  magneticPrimitive,
  parallaxLayersPrimitive,
  repelPrimitive,
  tiltPrimitive,
  dissolveToDustPrimitive,
  glitchTextPrimitive,
  neonFlickerTextPrimitive,
  scramblePrimitive,
  splitStaggerPrimitive,
  textCascadePrimitive,
  textExtrudePrimitive,
  typewriterPrimitive,
  waveTextPrimitive,
  flagWavePrimitive,
  foamPrimitive,
  inkSpreadPrimitive,
  jellySurfacePrimitive,
  oceanFftPrimitive,
  ripplePrimitive,
  ripplePoolPrimitive,
  wavePrimitive,
  displacementTransitionPrimitive,
  glitchDisplacePrimitive,
  meltPrimitive,
  pixelDissolvePrimitive,
  shatterPrimitive,
  irisWipePrimitive,
  maskWipePrimitive,
  blurInPrimitive,
  zoomBlurPrimitive,
  holographicPrimitive,
  iridescencePrimitive,
  metallicSheenPrimitive,
  shimmerPrimitive,
  sparkleGlintsPrimitive,
  crystalFacetPrimitive,
  dispersionPrimitive,
  fresnelGlowPrimitive,
  frostedGlassPrimitive,
  glassRefractionPrimitive,
  iridescentGlassPrimitive,
  liquidGlassPrimitive,
  refractionWarpPrimitive,
  causticsPrimitive,
  causticsRipplePrimitive,
  underwaterCausticsPrimitive,
  cloudsPrimitive,
  fireFlamePrimitive,
  fogPrimitive,
  godrayPrimitive,
  lightShaftsPrimitive,
  nebulaPrimitive,
  plasmaPrimitive,
  smokePrimitive,
  steamPrimitive,
  wispySmokePrimitive,
  bubblesPrimitive,
  confettiPrimitive,
  dustParticlesPrimitive,
  embersPrimitive,
  firefliesPrimitive,
  fountainPrimitive,
  rainPrimitive,
  snowPrimitive,
  sparksPrimitive,
];

let registered = false;
export function registerAllPrimitives(): void {
  if (registered) return;
  for (const def of ALL_PRIMITIVES) registerPrimitive(def);
  registered = true;
}

registerAllPrimitives();
