'use client';

// Chassis material factory — the founder's WORN-ALLOY finish ("Iron Man's suit of
// armor": refined alloy, polished BUT worn, micro-scratches, brushed/satin grain,
// subtle patina + edge-wear). Each section gets a FULL generated PBR set (a tinted
// worn albedo + derived normal, roughness, metalness, and AO maps) applied in the
// metallic workflow, so the curated jewel-tone reads as a colored alloy and the
// grain/scratches catch light — never glossy plastic.
//
// Maps are generated by .assetgen/gen-chassis-worn.sh (FLUX.2 worn-metal plates)
// → .assetgen/derive-chassis-worn.mjs (bakes the section tint + derives the set).

import { useMemo } from 'react';
import { useTexture } from '@react-three/drei';
import * as THREE from 'three';
import { SECTIONS, TEXTURE_DIR } from './chassis-config';

export interface WornMaps {
  map: THREE.Texture;
  normalMap: THREE.Texture;
  roughnessMap: THREE.Texture;
  metalnessMap: THREE.Texture;
  aoMap: THREE.Texture;
}

// One PBR set per distinct section texture key.
const KEYS = Array.from(new Set(SECTIONS.map((s) => s.textureKey)));
const SUFFIX = ['albedo', 'normal', 'rough', 'metal', 'ao'] as const;

// Load every section's worn-alloy PBR set with correct color spaces. Must be
// called inside the Canvas tree (suspends until the textures stream in).
export function useWornMaps(): Record<string, WornMaps> {
  const urls: string[] = [];
  for (const key of KEYS) {
    for (const s of SUFFIX) urls.push(`${TEXTURE_DIR}/${key}-${s}.png`);
  }
  const textures = useTexture(urls) as THREE.Texture[];
  return useMemo(() => {
    const out: Record<string, WornMaps> = {};
    KEYS.forEach((key, ki) => {
      const base = ki * SUFFIX.length;
      const map = textures[base];
      const normalMap = textures[base + 1];
      const roughnessMap = textures[base + 2];
      const metalnessMap = textures[base + 3];
      const aoMap = textures[base + 4];
      map.colorSpace = THREE.SRGBColorSpace;
      for (const t of [normalMap, roughnessMap, metalnessMap, aoMap]) {
        t.colorSpace = THREE.NoColorSpace;
      }
      for (const t of [map, normalMap, roughnessMap, metalnessMap, aoMap]) {
        t.anisotropy = 8;
        // seamless allover worn-metal tile → repeat a touch so each small cube
        // face shows dense brushed grain + scratches (the finish reads as metal).
        t.wrapS = t.wrapT = THREE.RepeatWrapping;
        t.repeat.set(1.5, 1.5);
        t.needsUpdate = true;
      }
      out[key] = { map, normalMap, roughnessMap, metalnessMap, aoMap };
    });
    return out;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [textures]);
}

// Apply the worn-alloy PBR maps to a MeshPhysicalMaterial in the metallic workflow.
// The albedo already carries the baked jewel-tone, so `color` stays white; the
// roughness/metalness maps carry the satin range; a thin worn clearcoat + faint
// anisotropy sell the brushed-but-used metal.
export function applyWornMaterial(mat: THREE.MeshPhysicalMaterial, maps: WornMaps) {
  mat.map = maps.map;
  mat.color = new THREE.Color('#ffffff');
  mat.normalMap = maps.normalMap;
  mat.normalScale = new THREE.Vector2(1.15, 1.15); // pronounced brushed grain + scratch relief
  mat.roughnessMap = maps.roughnessMap;
  mat.roughness = 1; // map carries the satin [0.26..0.62] range
  mat.metalnessMap = maps.metalnessMap;
  mat.metalness = 1; // map carries the high-alloy range
  mat.aoMap = maps.aoMap; // needs uv1 — set on the geometry in the button
  mat.aoMapIntensity = 0.9;
  mat.clearcoat = 0.12; // a whisper of satin clear, not a wet/candy gloss
  mat.clearcoatRoughness = 0.6;
  mat.envMapIntensity = 1.1;
  // Brushed-metal directional highlight along the grain.
  mat.anisotropy = 0.4;
  mat.anisotropyRotation = Math.PI / 2;
  mat.needsUpdate = true;
}
