'use client';

// Exotic family — thin-film iridescence, soap interference, and self-emissive
// materials for the Prism material library. These lean on MeshPhysicalMaterial's
// iridescence stack (iridescence + iridescenceIOR + iridescenceThicknessRange,
// the latter setting the visible hue band) plus emissive for the glow members.
// Tuned to read photoreal under a studio HDRI + AgX/AGX tonemap — soap films
// and oil slicks throw shifting spectral sheens, not flat candy colour.

import type { MaterialDef } from '../material-types';

export const EXOTIC: MaterialDef[] = [
  {
    id: 'exotic.oil-slick',
    family: 'Exotic',
    label: 'Oil Slick',
    params: {
      baseColor: '#0a0c12',
      metalness: 0.9,
      roughness: 0.18,
      clearcoat: 0.7,
      clearcoatRoughness: 0.22,
      iridescence: 1,
      iridescenceIOR: 1.32,
      iridescenceThicknessRange: [200, 800],
      envMapIntensity: 1.15,
      specularIntensity: 1,
    },
    swatchTint: '#2a3d6b',
  },
  {
    id: 'exotic.soap-film',
    family: 'Exotic',
    label: 'Soap Film',
    params: {
      baseColor: '#ffffff',
      metalness: 0,
      roughness: 0.03,
      transmission: 1,
      ior: 1.33,
      thickness: 0.04,
      iridescence: 1,
      iridescenceIOR: 1.4,
      iridescenceThicknessRange: [120, 520],
      clearcoat: 0.5,
      clearcoatRoughness: 0.04,
      envMapIntensity: 1.2,
      specularIntensity: 1,
    },
    swatchTint: '#9fe6d0',
  },
  {
    id: 'exotic.holographic-foil',
    family: 'Exotic',
    label: 'Holographic Foil',
    params: {
      baseColor: '#c8ccd4',
      metalness: 1,
      roughness: 0.12,
      clearcoat: 1,
      clearcoatRoughness: 0.08,
      iridescence: 1,
      iridescenceIOR: 1.8,
      iridescenceThicknessRange: [300, 1000],
      envMapIntensity: 1.3,
      specularIntensity: 1,
    },
    swatchTint: '#b59cff',
  },
  {
    id: 'exotic.nacre',
    family: 'Exotic',
    label: 'Mother of Pearl',
    params: {
      baseColor: '#f3ece4',
      metalness: 0.2,
      roughness: 0.28,
      clearcoat: 0.6,
      clearcoatRoughness: 0.18,
      sheen: 0.4,
      sheenRoughness: 0.4,
      sheenColor: '#ffe9f4',
      iridescence: 0.8,
      iridescenceIOR: 1.6,
      iridescenceThicknessRange: [350, 720],
      envMapIntensity: 1,
    },
    swatchTint: '#ecdfe6',
  },
  {
    id: 'exotic.scarab-shell',
    family: 'Exotic',
    label: 'Scarab Shell',
    params: {
      baseColor: '#16361f',
      metalness: 0.95,
      roughness: 0.2,
      clearcoat: 0.85,
      clearcoatRoughness: 0.12,
      iridescence: 1,
      iridescenceIOR: 1.45,
      iridescenceThicknessRange: [280, 620],
      envMapIntensity: 1.1,
      specularIntensity: 1,
    },
    swatchTint: '#3f7a3a',
  },
  {
    id: 'exotic.patina-copper',
    family: 'Exotic',
    label: 'Verdigris Patina',
    params: {
      baseColor: '#4a8a78',
      metalness: 0.15,
      roughness: 0.78,
      clearcoat: 0.08,
      clearcoatRoughness: 0.6,
      envMapIntensity: 0.6,
      wear: 0.85,
      normalScale: 1.2,
    },
    swatchTint: '#4f9583',
  },
  {
    id: 'exotic.anodized-titanium',
    family: 'Exotic',
    label: 'Anodized Titanium',
    params: {
      baseColor: '#6b7080',
      metalness: 1,
      roughness: 0.34,
      iridescence: 0.9,
      iridescenceIOR: 1.5,
      iridescenceThicknessRange: [400, 880],
      envMapIntensity: 1,
      anisotropy: 0.3,
      anisotropyRotation: Math.PI / 3,
      specularIntensity: 1,
    },
    swatchTint: '#5d6f99',
  },
  {
    id: 'exotic.bioluminescent',
    family: 'Exotic',
    label: 'Bioluminescent',
    params: {
      baseColor: '#06201c',
      metalness: 0,
      roughness: 0.42,
      transmission: 0.3,
      ior: 1.4,
      thickness: 0.5,
      attenuationColor: '#0c5a4a',
      attenuationDistance: 0.6,
      emissive: '#1cffc4',
      emissiveIntensity: 2.4,
      clearcoat: 0.4,
      clearcoatRoughness: 0.2,
      envMapIntensity: 0.7,
    },
    swatchTint: '#1cffc4',
  },
  {
    id: 'exotic.abyssal-glow',
    family: 'Exotic',
    label: 'Abyssal Glow',
    params: {
      baseColor: '#040a14',
      metalness: 0,
      roughness: 0.5,
      transmission: 0.2,
      ior: 1.42,
      thickness: 0.7,
      attenuationColor: '#062338',
      attenuationDistance: 0.45,
      emissive: '#2e7bff',
      emissiveIntensity: 1.8,
      iridescence: 0.6,
      iridescenceIOR: 1.5,
      iridescenceThicknessRange: [260, 700],
      envMapIntensity: 0.6,
    },
    swatchTint: '#2e7bff',
  },
];
